"""
insight_reporter.py — InsightReporter Agent
Responsible for: aggregating all agent outputs into Markdown + JSON reports
Part of DataSense AI multi-agent analytics platform
"""

import os
import json
from datetime import datetime


class InsightReporterAgent:

    def __init__(self, output_dir: str = "outputs"):
        self.name = "InsightReporter"
        self.output_dir = output_dir
        self.context = {}

        os.makedirs(output_dir, exist_ok=True)

        print(f"[{self.name}] Agent initialized")

    # ---------------------------------------------------------
    # RECEIVE CONTEXT
    # ---------------------------------------------------------
    def receive_context(self, full_context: dict):

        self.context = full_context

        print(f"[{self.name}] Received full pipeline context - generating reports...")

    # ---------------------------------------------------------
    # GENERATE MARKDOWN REPORT
    # ---------------------------------------------------------
    def generate_markdown_report(self) -> str:

        ctx = self.context
        now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        da = ctx.get("data_analyst", {})
        se = ctx.get("statistics", {})
        ml = ctx.get("ml", {})
        fc = ctx.get("forecast", {})

        profile = da.get("profile", {})
        stats = se.get("stats_report", {})
        ml_results = ml.get("ml_results", {})
        fc_results = fc.get("forecast_results", {})

        md = f"""
# DataSense AI - Analytics Report

Generated by: DataSense AI Multi-Agent Platform
Timestamp: {now}

------------------------------------------------------------

## Executive Summary

This report presents automated analysis of the e-commerce sales dataset.

### Dataset Information

- Dataset Shape: {profile.get('shape', 'N/A')}
- Numeric Features: {len(profile.get('numeric_columns', []))}
- Categorical Features: {len(profile.get('categorical_columns', []))}
- Date Columns: {len(profile.get('datetime_columns', []))}
- Missing Values: {sum(profile.get('missing_values', {}).values())}

------------------------------------------------------------

## Data Quality Assessment

- Dataset cleaned and validated by DataAnalyst agent
- Duplicate rows removed
- Datetime columns parsed automatically
- Missing values filled using median/mode methods

------------------------------------------------------------

## Statistical Analysis

### Normality Testing

| Column | Statistic | P-Value | Normal |
|--------|------------|----------|---------|
"""

        normality = stats.get("normality", {})

        for col, v in normality.items():

            status = "YES" if v["is_normal"] else "NO"

            md += f"| {col} | {v['statistic']} | {v['p_value']} | {status} |\n"

        md += """

------------------------------------------------------------

## Machine Learning Results

"""

        rf = ml_results.get("random_forest", {})
        svm_r = ml_results.get("svm", {})
        pca_r = ml_results.get("pca", {})
        km_r = ml_results.get("kmeans", {})

        md += """
### PCA Results

| Component | Variance Explained |
|-----------|--------------------|
"""

        for i, v in enumerate(pca_r.get("explained_variance_ratio", []), 1):
            md += f"| PC{i} | {v:.1%} |\n"

        md += f"| TOTAL | {pca_r.get('cumulative_variance', 0):.1%} |\n"

        md += f"""

### KMeans Clustering

- Number of Clusters: {km_r.get('n_clusters', 'N/A')}
- Silhouette Score: {km_r.get('silhouette_score', 'N/A')}
- Inertia: {km_r.get('inertia', 'N/A')}

### Random Forest

- Accuracy: {rf.get('accuracy', 'N/A')}
- Cross Validation Mean: {rf.get('cv_mean', 'N/A')}

### Support Vector Machine

- Kernel: {svm_r.get('kernel', 'N/A')}
- Accuracy: {svm_r.get('accuracy', 'N/A')}

------------------------------------------------------------

## Forecast Results

"""

        summary = fc_results.get("forecast_summary", {})

        md += f"""
- Forecast Model: {fc_results.get('model', 'N/A')}
- MAE: {fc_results.get('mae', 'N/A')}
- RMSE: {fc_results.get('rmse', 'N/A')}
- Forecast Mean: {summary.get('mean', 'N/A')}
- 30-Day Forecast Total: {summary.get('total', 'N/A')}

------------------------------------------------------------

## Output Files

- forecast_chart.png
- correlation_heatmap.png
- distributions.png
- boxplots.png
- data_profile.json
- statistics_report.json
- ml_results.json
- forecast_results.json
- summary.json

------------------------------------------------------------

## Agent Architecture

User Query
    ->
ScraperAgent
    ->
DataAnalyst
    ->
StatisticsEngine
    ->
MLOrchestrator
    ->
ForecastingAgent
    ->
InsightReporter

------------------------------------------------------------

Report generated by DataSense AI
"""

        path = os.path.join(self.output_dir, "report.md")

        with open(path, "w", encoding="utf-8") as f:
            f.write(md)

        print(f"[{self.name}] Markdown report saved -> {path}")

        return path

    # ---------------------------------------------------------
    # GENERATE JSON SUMMARY
    # ---------------------------------------------------------
    def generate_json_summary(self) -> str:

        ctx = self.context

        summary = {
            "pipeline": "DataSense AI",

            "timestamp": datetime.now().isoformat(),

            "agents_used": [
                "ScraperAgent",
                "DataAnalyst",
                "StatisticsEngine",
                "MLOrchestrator",
                "ForecastingAgent",
                "InsightReporter"
            ],

            "data_profile": ctx.get(
                "data_analyst", {}
            ).get(
                "profile", {}
            ),

            "ml_summary": ctx.get(
                "ml", {}
            ).get(
                "ml_results", {}
            ),

            "forecast_summary": ctx.get(
                "forecast", {}
            ).get(
                "forecast_results", {}
            ).get(
                "forecast_summary", {}
            ),
        }

        path = os.path.join(self.output_dir, "summary.json")

        with open(path, "w") as f:
            json.dump(summary, f, indent=2, default=str)

        print(f"[{self.name}] JSON summary saved -> {path}")

        return path